repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.6
  hooks:
    - id: ruff
      args: [--fix, --preview]
      exclude: tests/resources/|playgrounds/
    - id: ruff-format
      exclude: tests/resources/|playgrounds/
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.7.1
  hooks:
  -   id: mypy
      args: [ --ignore-missing-imports ]
      files: "src/"
      exclude: tests/resources/
