[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pycodehash"
description = ""
readme = "README.md"
requires-python = ">=3.7"
license = {text = "MIT License"}
classifiers = [
    "Programming Language :: Python :: 3",
]
authors = [
  { name = "Max Baak", email = "max.baak@ing.com" },
  { name = "Simon Brugman", email = "simon.brugman@ing.com" },
  { name = "Ralph Urlus", email = "ralph.urlus@ing.com" },
]

dynamic = ["version"]

[tool.hatch.version]
path = "src/pycodehash/version.py"

dependencies = [
    'astunparse; python_version <= "3.9"',
]

[project.urls]
Source = "https://github.com/RUrlus/pycodehash"
Documentation = "https://github.com/RUrlus/pycodehash#readme"
Issues = "https://github.com/RUrlus/pycodehash/issues"

[tool.hatch.metadata]
allow-direct-references = true
