[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "example"
version = "0.1.0"
description = "Testing library for pycodehash"
requires-python = ">=3.7"
authors = [
  { name = "x", email = "x@x.com" },
]

dependencies = []
