name: build

on:
  push:
    branches: [ main, dev ]
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ['3.8', '3.9', '3.10', '3.11']
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tests/resources/tliba tests/resources/tlibb
        pip install -e .[test]
    - name: Lint with pre-commit
      run: |
        pip install pre-commit
        pre-commit run --all-files
    - name: Test with pytest
      run: |
        pytest
